package org.example.utils;

import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;

/**
 * A singleton service for collecting and providing various application statistics.
 * This includes counts of generated IDs, IDs assigned to different entity types,
 * task execution frequencies, and thread-level task distribution.
 * All statistics are stored in concurrent data structures to ensure thread safety.
 */
public class StatisticsService {

    private static StatisticsService instance;

    private final AtomicLong totalGeneratedIds;
    private final ConcurrentHashMap<String, AtomicInteger> idsGeneratedByComponent;
    private final ConcurrentHashMap<String, Set<Long>> idsAssignedToEntityType;
    private final ConcurrentHashMap<String, AtomicInteger> taskExecutionCounts;
    private final ConcurrentHashMap<String, ConcurrentHashMap<String, AtomicInteger>> threadTaskExecutionCounts;

    private StatisticsService() {
        totalGeneratedIds = new AtomicLong(0);
        idsGeneratedByComponent = new ConcurrentHashMap<>();
        idsAssignedToEntityType = new ConcurrentHashMap<>();
        taskExecutionCounts = new ConcurrentHashMap<>();
        threadTaskExecutionCounts = new ConcurrentHashMap<>();
    }

    /**
     * Returns the singleton instance of the StatisticsService.
     * Uses synchronized access for lazy initialization.
     *
     * @return The single instance of {@code StatisticsService}.
     */
    public static synchronized StatisticsService getInstance() {
        if (instance == null) {
            instance = new StatisticsService();
        }
        return instance;
    }

    /**
     * Records that an ID has been generated by a specific component.
     * Increments the total count of generated IDs and the count for the given component.
     *
     * @param componentName The name of the component that generated the ID (e.g., "SharedIDService").
     */
    public void recordIdGenerated(String componentName) {
        totalGeneratedIds.incrementAndGet();
        idsGeneratedByComponent.computeIfAbsent(componentName, k -> new AtomicInteger(0)).incrementAndGet();
    }

    /**
     * Records that an ID has been assigned to a specific type of entity.
     * This helps track how many unique entities of each type exist.
     *
     * @param entityType The type of the entity (e.g., "Customer", "Event", "Ticket").
     * @param id The ID that was assigned.
     */
    public void recordIdAssigned(String entityType, long id) {
        idsAssignedToEntityType.computeIfAbsent(entityType, k -> ConcurrentHashMap.newKeySet()).add(id);
    }

    /**
     * Records the execution of a specific task, including the thread pool and thread that executed it.
     *
     * @param taskName The name of the task (e.g., "CreateEventTask", "PrimeSearchSegment").
     * @param threadPoolName The name of the thread pool the task ran in (e.g., "PerformanceClientExecutor", "PrimeSearcherPool").
     * @param threadName The name of the thread that executed the task.
     */
    public void recordTaskExecution(String taskName, String threadPoolName, String threadName) {
        taskExecutionCounts.computeIfAbsent(taskName, k -> new AtomicInteger(0)).incrementAndGet();
        threadTaskExecutionCounts.computeIfAbsent(threadPoolName, k -> new ConcurrentHashMap<>())
                .computeIfAbsent(threadName, k -> new AtomicInteger(0)).incrementAndGet();
    }

    /**
     * Generates a string representation of all collected statistics.
     * This includes total IDs generated, IDs per component, IDs per entity type,
     * task execution counts, and thread-level task distribution.
     *
     * @return A formatted string containing all collected statistics.
     */
    public String getStatistics() {
        StringBuilder sb = new StringBuilder();
        sb.append("--- Statistics ---").append(System.lineSeparator());
        sb.append("Total IDs Generated: ").append(totalGeneratedIds.get()).append(System.lineSeparator());
        sb.append(System.lineSeparator());

        sb.append("IDs Generated by Component:").append(System.lineSeparator());
        if (idsGeneratedByComponent.isEmpty()) {
            sb.append("  None").append(System.lineSeparator());
        } else {
            for (Map.Entry<String, AtomicInteger> entry : idsGeneratedByComponent.entrySet()) {
                sb.append("  - ").append(entry.getKey()).append(": ").append(entry.getValue().get()).append(System.lineSeparator());
            }
        }
        sb.append(System.lineSeparator());

        sb.append("Number of IDs Assigned to Entity Type:").append(System.lineSeparator());
        if (idsAssignedToEntityType.isEmpty()) {
            sb.append("  None").append(System.lineSeparator());
        } else {
            for (Map.Entry<String, Set<Long>> entry : idsAssignedToEntityType.entrySet()) {
                sb.append("  - ").append(entry.getKey()).append(": ").append(entry.getValue().size()).append(System.lineSeparator());
            }
        }
        sb.append(System.lineSeparator());

        sb.append("Task Execution Counts:").append(System.lineSeparator());
        if (taskExecutionCounts.isEmpty()) {
            sb.append("  None").append(System.lineSeparator());
        } else {
            for (Map.Entry<String, AtomicInteger> entry : taskExecutionCounts.entrySet()) {
                sb.append("  - ").append(entry.getKey()).append(": ").append(entry.getValue().get()).append(System.lineSeparator());
            }
        }
        sb.append(System.lineSeparator());

        sb.append("Thread Task Execution Counts:").append(System.lineSeparator());
        if (threadTaskExecutionCounts.isEmpty()) {
            sb.append("  None").append(System.lineSeparator());
        } else {
            for (Map.Entry<String, ConcurrentHashMap<String, AtomicInteger>> poolEntry : threadTaskExecutionCounts.entrySet()) {
                sb.append("  Thread Pool: ").append(poolEntry.getKey()).append(System.lineSeparator());
                if (poolEntry.getValue().isEmpty()) {
                    sb.append("    No tasks executed by threads in this pool.").append(System.lineSeparator());
                } else {
                    for (Map.Entry<String, AtomicInteger> threadEntry : poolEntry.getValue().entrySet()) {
                        sb.append("    - Thread: ").append(threadEntry.getKey()).append(", Executed Tasks: ").append(threadEntry.getValue().get()).append(System.lineSeparator());
                    }
                }
            }
        }
        sb.append("--- End of Statistics ---").append(System.lineSeparator());
        return sb.toString();
    }

    /**
     * Resets all collected statistics to their initial states (zero or empty).
     * This is useful for clearing data between test runs or application cycles.
     */
    public void reset() {
        totalGeneratedIds.set(0);
        idsGeneratedByComponent.clear();
        idsAssignedToEntityType.clear();
        taskExecutionCounts.clear();
        threadTaskExecutionCounts.clear();
    }
}
